"""add prompt test cases

Revision ID: 39dd199d07c3
Revises: d3c24ba1eb37
Create Date: 2026-08-24 18:43:45.537155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dd199d07c3'
down_revision: Union[str, Sequence[str], None] = 'd3c24ba1eb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('expected_contains', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_test_cases_id'), 'prompt_test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_test_cases_prompt_id'), 'prompt_test_cases', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_test_cases_prompt_id'), table_name='prompt_test_cases')
    op.drop_index(op.f('ix_prompt_test_cases_id'), table_name='prompt_test_cases')
    op.drop_table('prompt_test_cases')
    # ### end Alembic commands ###
