"""add prompt runs

Revision ID: 983c7a107e95
Revises: ca8f73b7c5ab
Create Date: 2026-08-22 22:30:29.671283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983c7a107e95'
down_revision: Union[str, Sequence[str], None] = 'ca8f73b7c5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_runs_created_at'), 'prompt_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_runs_id'), 'prompt_runs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_runs_prompt_id'), 'prompt_runs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_runs_provider'), 'prompt_runs', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_runs_provider'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_prompt_id'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_id'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_created_at'), table_name='prompt_runs')
    op.drop_table('prompt_runs')
    # ### end Alembic commands ###
