"""add prompt test suite history

Revision ID: d3ade7d285d5
Revises: 39dd199d07c3
Create Date: 2026-08-24 23:49:06.587193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ade7d285d5'
down_revision: Union[str, Sequence[str], None] = '39dd199d07c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_test_suite_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('total_assertions', sa.Integer(), nullable=False),
    sa.Column('passed_assertions', sa.Integer(), nullable=False),
    sa.Column('failed_assertions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_test_suite_runs_created_at'), 'prompt_test_suite_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_test_suite_runs_id'), 'prompt_test_suite_runs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_test_suite_runs_prompt_id'), 'prompt_test_suite_runs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_test_suite_runs_provider'), 'prompt_test_suite_runs', ['provider'], unique=False)
    op.create_table('prompt_test_case_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('prompt_run_id', sa.Integer(), nullable=True),
    sa.Column('test_case_name', sa.String(length=200), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_run_id'], ['prompt_test_suite_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['prompt_test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_test_case_results_id'), 'prompt_test_case_results', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_test_case_results_prompt_run_id'), 'prompt_test_case_results', ['prompt_run_id'], unique=False)
    op.create_index(op.f('ix_prompt_test_case_results_suite_run_id'), 'prompt_test_case_results', ['suite_run_id'], unique=False)
    op.create_index(op.f('ix_prompt_test_case_results_test_case_id'), 'prompt_test_case_results', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_test_case_results_test_case_id'), table_name='prompt_test_case_results')
    op.drop_index(op.f('ix_prompt_test_case_results_suite_run_id'), table_name='prompt_test_case_results')
    op.drop_index(op.f('ix_prompt_test_case_results_prompt_run_id'), table_name='prompt_test_case_results')
    op.drop_index(op.f('ix_prompt_test_case_results_id'), table_name='prompt_test_case_results')
    op.drop_table('prompt_test_case_results')
    op.drop_index(op.f('ix_prompt_test_suite_runs_provider'), table_name='prompt_test_suite_runs')
    op.drop_index(op.f('ix_prompt_test_suite_runs_prompt_id'), table_name='prompt_test_suite_runs')
    op.drop_index(op.f('ix_prompt_test_suite_runs_id'), table_name='prompt_test_suite_runs')
    op.drop_index(op.f('ix_prompt_test_suite_runs_created_at'), table_name='prompt_test_suite_runs')
    op.drop_table('prompt_test_suite_runs')
    # ### end Alembic commands ###
