"""add execution settings to prompt runs

Revision ID: d3c24ba1eb37
Revises: 983c7a107e95
Create Date: 2026-08-24 17:30:38.598300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c24ba1eb37'
down_revision: Union[str, Sequence[str], None] = '983c7a107e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_runs', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('prompt_runs', sa.Column('max_output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_runs', 'max_output_tokens')
    op.drop_column('prompt_runs', 'temperature')
    # ### end Alembic commands ###
